#!/bin/bash

delay="${1:-10}"  # default = 10 seconds

filename="$HOME/Pictures/Screenshots/screenshot-from-$(date +%Y-%m-%d_%H-%M-%S).png"

scrot -d "$delay" -c -p "$filename" && \
xclip -selection clipboard -t image/png -i "$filename" && \
paplay /usr/share/sounds/freedesktop/stereo/complete.oga
